NAME = libft.a

HEADER  = libft.h

CC = gcc
CFLAGS = -Wall -Werror -Wextra

AR = ar rc
RM = rm -f

BSRCS = $(wildcard *lst*.c)
SRCS = $(filter-out $(BSRCS), $(wildcard *.c))

BOBJS = $(BSRCS: .c=.o)
OBJS = $(SRCS : .c=.o))

all : $(NAME)

$(NAME) : $(OBJS)
			$(AR) $@ $^

bonus : $(BOBJS) $(OBJS)
		$(AR) $(NAME) $^

.c.o : $(SRCS) $(HEADER)
	$(CC) $(CFLAGS) -c $< -o $@

clean :
	$(RM) $(OBJS) $(BOBJS)

fclean : clean
	$(RM) $(NAME)

re : fclean all
